name: Build Gradle Java Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java 8
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # Step 3: Grant execute permissions for Gradle Wrapper
    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    # Step 4: Build the project
    - name: Build with Gradle
      run: ./gradlew build

    # Step 5: Upload the built JAR as an artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: mod-jar
        path: build/libs/*.jar
